#!/usr/bin/env python2.7
#
# By: Jonathan M. Cameron
#
# Copyright (c) 2015 Jonathan M. Cameron
# License: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

import os
import datetime
import calendar
import pytz
import argparse
import sqlite3

db_file_dir = os.environ.get('COUNT_DOWNLOADS_DB_PATH', '.')
database_filename = os.path.join(db_file_dir, 'downloads.db')

# Get the timezone
time_zone = os.environ.get('COUNT_DOWNLOADS_TZONE', 'America/Los_Angeles')

# Set up the arguments
parser = argparse.ArgumentParser()

args = parser.parse_args()

# Set up the database
conn = sqlite3.connect(database_filename)
cursor = conn.cursor()

# Step 1 - Get the unique filenames
sql = "SELECT DISTINCT filename FROM downloads"
cursor.execute(sql)
filenames = [f[0] for f in cursor.fetchall()]

# Step 2 - Now get the counts for each
counts = []
for fn in filenames:
    sql = "SELECT filename, count(*) FROM downloads WHERE filename='%s'" % fn
    cursor.execute(sql)
    data = cursor.fetchall()[0]
    counts.append((data[1], data[0]))

sql = "SELECT MAX(time) as max_time from downloads"
cursor.execute(sql)
max_date = cursor.fetchone()[0]

conn.commit()
conn.close()

# Step 3 - Print out the results
counts = sorted(counts, reverse=True)
print
print "TOTALS: "
for (num, fn) in counts:
    print " %5d %s" % (num, fn)

print
date = datetime.datetime.strptime(max_date + ' UTC', '%Y-%m-%d %H:%M:%S %Z')
utc_dt = date.replace(tzinfo=pytz.timezone('UTC'))
local_tz = pytz.timezone(time_zone)
local_dt = utc_dt.replace(tzinfo=pytz.utc).astimezone(local_tz)
print "Last Download: ", local_dt.strftime('%c %Z')
print
