#!/usr/bin/env python2.7
#
# By: Jonathan M. Cameron
#
# Copyright (c) 2015 Jonathan M. Cameron
# License: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

import os, sys
import sqlite3

db_file_dir = os.environ.get('COUNT_DOWNLOADS_DB_PATH', '.')
database_filename = os.path.join(db_file_dir, 'downloads.db')

print "Purging all zero-length downloads..."
print
print "Proceed? (Y/n)",
ans = raw_input()

if not ans or ans[0] != 'y':
    print "Aborting!"
    sys.exit()
else:
    print

# Set up the database
conn = sqlite3.connect(database_filename)
cursor = conn.cursor()

query = "DELETE from downloads WHERE size='0'"
cursor.execute(query)

conn.commit()
conn.close()

print "Done"
